---
- name: Install Wordpress, MySQL, Nginx, and PHP-FPM
  hosts: "141"
  user: ansible
  sudo: yes
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mysql 
    - nginx
    - php-fpm
    - wordpress
